Fixes https://gist.github.com/garethrees/42ca8dd64182515d6aa90000463ebfe1.

diff --git a/src/test/locale/de_DE.ISO8859-1/runall b/src/test/locale/de_DE.ISO8859-1/runall
--- a/src/test/locale/de_DE.ISO8859-1/runall
+++ b/src/test/locale/de_DE.ISO8859-1/runall
@@ -57,8 +57,8 @@ for f in char varchar text; do
    diff expected/test-de-upper-$f.sql.out test-de-upper-$f.sql.out
 done
 
-echo "Testing PgSQL: select on regexp..."
-psql -X testlocale < test-de-select.sql.in > test-de-select.sql.out 2>/dev/null || abort "select query failed"
-diff expected/test-de-select.sql.out test-de-select.sql.out
+echo "Testing PgSQL: selext on regexp..."
+psql -X testlocale < test-de-selext.sql.in > test-de-selext.sql.out 2>/dev/null || abort "selext query failed"
+diff expected/test-de-selext.sql.out test-de-selext.sql.out
 dropdb testlocale || abort "dropdb failed"
 echo "Finished."
diff --git a/src/test/locale/gr_GR.ISO8859-7/runall b/src/test/locale/gr_GR.ISO8859-7/runall
--- a/src/test/locale/gr_GR.ISO8859-7/runall
+++ b/src/test/locale/gr_GR.ISO8859-7/runall
@@ -42,8 +42,8 @@ for f in char varchar text; do
    psql -X testlocale < test-gr.sql.in > test-gr-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-gr-$f.sql.out test-gr-$f.sql.out
 done
-echo "Testing PgSQL: select on regexp..."
-psql -X testlocale < test-gr-select.sql.in > test-gr-select.sql.out 2>/dev/null || abort "select query failed"
-diff expected/test-gr-select.sql.out test-gr-select.sql.out
+echo "Testing PgSQL: selext on regexp..."
+psql -X testlocale < test-gr-selext.sql.in > test-gr-selext.sql.out 2>/dev/null || abort "selext query failed"
+diff expected/test-gr-selext.sql.out test-gr-selext.sql.out
 dropdb testlocale || abort "dropdb failed"
 echo "Finished."
diff --git a/src/test/locale/koi8-to-win1251/runall b/src/test/locale/koi8-to-win1251/runall
--- a/src/test/locale/koi8-to-win1251/runall
+++ b/src/test/locale/koi8-to-win1251/runall
@@ -39,8 +39,8 @@ for f in char varchar text; do
    psql -X testlocale < test-koi8.sql.in > test-koi8-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-koi8-$f.sql.out test-koi8-$f.sql.out
 done
-echo "Testing PgSQL: select on regexp..."
-psql -X testlocale < test-koi8-select.sql.in > test-koi8-select.sql.out 2>/dev/null || abort "select query failed"
-diff expected/test-koi8-select.sql.out test-koi8-select.sql.out
+echo "Testing PgSQL: selext on regexp..."
+psql -X testlocale < test-koi8-selext.sql.in > test-koi8-selext.sql.out 2>/dev/null || abort "selext query failed"
+diff expected/test-koi8-selext.sql.out test-koi8-selext.sql.out
 dropdb testlocale || abort "dropdb failed"
 echo "Finished."
